[alias]
lint = "clippy --workspace --all-targets --all-features -- -Dclippy::all -Dclippy::pedantic"
fixit = "clippy --fix --allow-dirty --allow-staged --workspace --all-targets --all-features -- -Dclippy::all -Dclippy::pedantic"
